import { Search, Network, Wifi, FolderOpen, Bug, Key, Clock, Filter, Database, Code, Shield, Server, Link, Terminal, FileText, MousePointer, Gauge, Lock, Brain, Plug, Smartphone, Monitor, Eye } from "lucide-react";

export const securityCategories = [
  {
    id: "reconnaissance",
    name: "Reconnaissance",
    description: "Information gathering and enumeration",
    icon: Search,
  },
  {
    id: "subdomainEnumeration",
    name: "Subdomain Enumeration",
    description: "DNS subdomain discovery and mapping",
    icon: Network,
  },
  {
    id: "portScanning",
    name: "Port Scanning",
    description: "Open port detection and service enumeration",
    icon: Wifi,
  },
  {
    id: "directoryEnumeration",
    name: "Directory Enumeration",
    description: "Hidden directories and endpoint discovery",
    icon: FolderOpen,
  },
  {
    id: "vulnerabilityScanning",
    name: "Vulnerability Scanning",
    description: "Automated vulnerability detection",
    icon: Bug,
  },
  {
    id: "manualTesting",
    name: "Manual Testing",
    description: "Manual security testing procedures",
    icon: Search,
  },
  {
    id: "authenticationTesting",
    name: "Authentication Testing",
    description: "Login mechanisms and bypass testing",
    icon: Key,
  },
  {
    id: "sessionManagement",
    name: "Session Management",
    description: "Session handling and security testing",
    icon: Clock,
  },
  {
    id: "inputValidation",
    name: "Input Validation",
    description: "Data validation and sanitization testing",
    icon: Filter,
  },
  {
    id: "sqlInjection",
    name: "SQL Injection",
    description: "Database injection vulnerability testing",
    icon: Database,
  },
  {
    id: "xss",
    name: "XSS (Cross-Site Scripting)",
    description: "Client-side script injection testing",
    icon: Code,
  },
  {
    id: "csrf",
    name: "CSRF Protection",
    description: "Cross-site request forgery testing",
    icon: Shield,
  },
  {
    id: "ssrf",
    name: "SSRF Testing",
    description: "Server-side request forgery detection",
    icon: Server,
  },
  {
    id: "idor",
    name: "IDOR Testing",
    description: "Insecure direct object reference testing",
    icon: Link,
  },
  {
    id: "rce",
    name: "RCE Testing",
    description: "Remote code execution vulnerability testing",
    icon: Terminal,
  },
  {
    id: "fileInclusion",
    name: "File Inclusion",
    description: "Local and remote file inclusion testing",
    icon: FileText,
  },
  {
    id: "clickjacking",
    name: "Clickjacking",
    description: "UI redressing attack testing",
    icon: MousePointer,
  },
  {
    id: "rateLimiting",
    name: "Rate Limiting",
    description: "Rate limiting bypass testing",
    icon: Gauge,
  },
  {
    id: "accessControl",
    name: "Access Control",
    description: "Authorization and privilege escalation",
    icon: Lock,
  },
  {
    id: "businessLogic",
    name: "Business Logic",
    description: "Application logic flaw testing",
    icon: Brain,
  },
  {
    id: "apiTesting",
    name: "API Testing",
    description: "API security vulnerability testing",
    icon: Plug,
  },
  {
    id: "mobileAppTesting",
    name: "Mobile App Testing",
    description: "Mobile-specific security vulnerabilities",
    icon: Smartphone,
  },
  {
    id: "clientSideVulns",
    name: "Client-side Vulnerabilities",
    description: "Frontend security issue detection",
    icon: Monitor,
  },
  {
    id: "informationDisclosure",
    name: "Information Disclosure",
    description: "Sensitive data exposure testing",
    icon: Eye,
  },
  {
    id: "serverSideVulns",
    name: "Server-side Vulnerabilities",
    description: "Backend security issue detection",
    icon: Server,
  },
];
