export const securityCategories = [
  {
    id: "reconnaissance",
    name: "Reconnaissance",
    description: "Information gathering and enumeration",
    icon: "Search",
  },
  {
    id: "subdomainEnumeration",
    name: "Subdomain Enumeration",
    description: "Subdomain discovery and analysis",
    icon: "Globe",
  },
  {
    id: "portScanning",
    name: "Port Scanning",
    description: "Network port discovery and analysis",
    icon: "Wifi",
  },
  {
    id: "directoryEnumeration",
    name: "Directory Enumeration",
    description: "Web directory and file discovery",
    icon: "Folder",
  },
  {
    id: "vulnerabilityScanning",
    name: "Vulnerability Scanning",
    description: "Automated vulnerability detection",
    icon: "Shield",
  },
  {
    id: "manualTesting",
    name: "Manual Testing",
    description: "Manual security testing procedures",
    icon: "User",
  },
  {
    id: "authenticationTesting",
    name: "Authentication Testing",
    description: "Authentication mechanism analysis",
    icon: "Lock",
  },
  {
    id: "sessionManagement",
    name: "Session Management",
    description: "Session handling security analysis",
    icon: "Clock",
  },
  {
    id: "inputValidation",
    name: "Input Validation",
    description: "Input validation and sanitization",
    icon: "Edit",
  },
  {
    id: "sqlInjection",
    name: "SQL Injection",
    description: "SQL injection vulnerability testing",
    icon: "Database",
  },
  {
    id: "xss",
    name: "Cross-Site Scripting",
    description: "XSS vulnerability detection",
    icon: "Code",
  },
  {
    id: "csrf",
    name: "CSRF",
    description: "Cross-Site Request Forgery testing",
    icon: "RefreshCw",
  },
  {
    id: "ssrf",
    name: "SSRF",
    description: "Server-Side Request Forgery analysis",
    icon: "Server",
  },
  {
    id: "idor",
    name: "IDOR",
    description: "Insecure Direct Object Reference testing",
    icon: "Key",
  },
  {
    id: "rce",
    name: "RCE",
    description: "Remote Code Execution vulnerability testing",
    icon: "Terminal",
  },
  {
    id: "fileInclusion",
    name: "File Inclusion",
    description: "File inclusion vulnerability analysis",
    icon: "FileText",
  },
  {
    id: "clickjacking",
    name: "Clickjacking",
    description: "Clickjacking attack prevention analysis",
    icon: "MousePointer",
  },
  {
    id: "rateLimiting",
    name: "Rate Limiting",
    description: "Rate limiting and DoS protection",
    icon: "Timer",
  },
  {
    id: "accessControl",
    name: "Access Control",
    description: "Authorization and access control testing",
    icon: "UserCheck",
  },
  {
    id: "businessLogic",
    name: "Business Logic",
    description: "Business logic vulnerability analysis",
    icon: "Briefcase",
  },
  {
    id: "apiTesting",
    name: "API Testing",
    description: "API security testing and analysis",
    icon: "Zap",
  },
  {
    id: "mobileAppTesting",
    name: "Mobile App Testing",
    description: "Mobile application security testing",
    icon: "Smartphone",
  },
  {
    id: "clientSideVulns",
    name: "Client-Side Vulnerabilities",
    description: "Client-side security analysis",
    icon: "Monitor",
  },
  {
    id: "informationDisclosure",
    name: "Information Disclosure",
    description: "Information leakage analysis",
    icon: "Eye",
  },
  {
    id: "serverSideVulns",
    name: "Server-Side Vulnerabilities",
    description: "Server-side security analysis",
    icon: "HardDrive",
  },
]
